title:            HungryMinds
description:      "Prototipando el futuro"
logo:             hungry_minds-logo.png
disqus_shortname: hmfaysal
share:            false
dropcap:			true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  /blog
gems: [jekyll-paginate]
future: true
# Owner/author information
owner:
  name:           HungryMinds
  avatar:         hmfaysal.jpg
  email:
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Prototipando el futuro
  # Social networking links used in footer. Update and remove as you like.
  # twitter:        hmfaysal
  facebook:       HungryMinds.io
  github:         HungryMinds
  instagram:      HungryMinds.io
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    https://plus.google.com/u/0/102602916593522619858

# Analytics and webmaster tools stuff goes here
google_analytics: UA-96188017-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
    external: false
    icon: home
  - title: Categorias
    url: /categories
  # - title: About
  #   url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future:      true
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

prose:
  rooturl: '_posts'
  siteurl: 'http://hmfaysal.github.io/Notepad/'
  relativeLinks: 'http://hmfaysal.github.io/Notepad/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "Categorias"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Angular"
              value: angular
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: "Hungry Minds!"
          placeholder: "Enter Post Headline"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
exclude: [vendor]